# Basic
title: Michael
subtitle: 写写代码，玩玩生活
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 你好，我是Michael！欢迎来到我的个人主页.</br>代码搬运工，目前就职于东方证券，任职H5/iOS高级研发工程师。
creator: <a href="http://michaelyb.top</a>

url: "http://www.michaelyb.top"

#enforce_ssl: "michaelyb.top"
#enforce_ssl: "michaelyb.com"

permalink: /:year/:month/:title/

# Format
# highlighter: rouge
# highlighter: pygments

# Jekyll 3.0 之后，会默认打开这一项，我们可以不用人为打开的
highlighter: rouge

# markdown: redcarpet
# redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]


markdown: kramdown
kramdown:
  input: GFM


# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: orange
#cover_color: purple
cover_color: green
#cover_color: red
#cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进入博客
nav:
    - {title: 全部, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于, description: 了解更多关于我, url: '/about/'}

    # - {title: 关于, description: 了解更多关于我, url: '/about/index.html'}
    # - {title: 关于我, description: about, url: '/about'}

# Navigation buttons in the front page.
# nav:
#     - {title: Projects, description: My Projects, url: 'http://project.xietao3.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
#gems: [jekyll-paginate]
#gems: [jekyll-paginate,jekyll-sitemap]
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: xietao3
    # duoshuo: xietao3
    livere: Michael
    # libili: Michael
    # livere: Michael  来必力
    
# Social
social:
    weibo: 爱就往死了爱
    github: Michaelyb520
    csdn: lcezyb520
  

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
