# Basic
title: Michael
#site_title: Michael's Blog <br/>天下事有难易乎？为之，则难者亦易矣；不为，则易者亦难矣。
subtitle: 写写代码，说说人生
welcome_message: H5 / Java / Objc / Swift / Vue / RN
#welcome_message: ObjC 中国与 objc.io 合作最新作品<a href="https://objccn.io/products/" target="_blank">《函数式 Swift》,《Core Data》,《Swift 进阶》及《集合类型优化》已经发布</a>，<a href="https://www.boxueio.com/register/ec84c3dd183b0acc820d5eae474d499d">泊学网正在开展订阅赠书活动，也欢迎前往了解</a>
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 你好，我是Michael，欢迎来到我的个人主页。</br>代码搬运工，目前就职于XX证券，任职高级软件研发工程师。
creator: <a href="http://michaelyb.top">@michaelyb</a>

url: "http://www.michaelyb.top"

#enforce_ssl: "michaelyb.top"
#enforce_ssl: "michaelyb.com"

permalink: /:year/:month/:title/

# Format
# highlighter: rouge
# highlighter: pygments

# Jekyll 3.0 之后，会默认打开这一项，我们可以不用人为打开的
highlighter: rouge

# markdown: redcarpet
# redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

markdown: kramdown
kramdown:
  input: GFM

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: orange
#cover_color: purple
cover_color: green
#cover_color: red
#cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进入博客
nav:
    - {title: 全部, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于我, description: about, url: '/about'}
    # - {title: 关于我, description: 了解更多关于我, url: '/about/'}
    # - {title: 关于我, description: 了解更多关于我, url: '/about/index.html'}

# Navigation buttons in the front page.
# nav:
#     - {title: Projects, description: My Projects, url: 'http://project.xietao3.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
#gems: [jekyll-paginate]
#gems: [jekyll-paginate,jekyll-sitemap]
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# 摘要
excerpt_separator: <!--excerpt-->

# Comment
comment:
    # disqus: xietao3
    # duoshuo: xietao3
    livere: Michael
    # libili: Michael
    # livere: Michael  来必力
    
# Social
social:
    weibo: 爱就往死了爱
    github: Michaelyb520
    csdn: lcezyb520
    mail: gdmichael520@163.com

# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: f23c3d4094ad48f36e3db36be61d1124

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
